name: flutter_package_example
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: 2.18.2
  flutter: 3.0.5
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: 2.1.0
  retrofit: 3.0.1+1
  json_annotation: 4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 2.2.0
  flutter_gen_runner: 4.3.0
  json_serializable: 6.3.1
  copy_with_extension_gen: 4.0.3
  flutter_oss_licenses: 2.0.1
  retrofit_generator: 4.0.3+1
  freezed: 2.1.0+1
flutter_gen:
  output: lib/gen/
  line_length: 120
  integrations:
    flutter_svg: true
  fonts:
    enabled: false
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/